language: c

sudo: required
dist: trusty

install:
 - sudo add-apt-repository -y ppa:gstreamer-developers/ppa
 - sudo apt-get update
 - sudo apt-get install -y
        gir1.2-gstreamer-1.0
        git
        make
        python-pytest
        python-pytest-xdist
        gstreamer1.0-plugins-bad
        gstreamer1.0-plugins-base
        gstreamer1.0-tools
        libgstreamer1.0-dev
        libgstreamer-plugins-base1.0-dev
        valac
        valgrind

script:
 - make prefix=/usr
 - make check
 - sudo make install prefix=/usr
